### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by misrarah** [morganstanley/ComposeUI#866]
Hi,

I wonder if I'm missing some setup. I cloned the repo and tried to run npm install which fails with the following if I use node 18.16.0 
```

35 verbose stack TypeError: Cannot set properties of null (setting 'peer')
35 verbose stack     at visit (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:104:54)
35 verbose stack     at visitNode (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:58:25)
35 verbose stack     at next (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:44:19)
35 verbose stack     at depth (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:83:10)
35 verbose stack     at depth (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\treeverse\lib\depth.js:27:12)
35 verbose stack     at unsetFlag (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:99:5)
35 verbose stack     at C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:65:7
35 verbose stack     at Map.forEach (<anonymous>)
35 verbose stack     at calcDepFlagsStep (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:41:17)
35 verbose stack     at visit (C:\Users\XXX\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:12:20)
36 verbose cwd C:\Users\XXX\source\repos\ComposeUI
37 verbose Windows_NT 10.0.22621
38 verbose node v18.16.0
39 verbose npm  v9.5.1
40 error Cannot set properties of null (setting 'peer')
41 verbose exit 1
42 timing npm Completed in 1240ms
```

I also tried using node 23.3.0 which moves a little bit further ahead and fails as following - 
```

5059 info run @morgan-stanley/composeui-node-launcher@0.1.0-alpha.4 install src/shell/js/composeui-node-launcher node ./src/cli/install.js
5060 info run @morgan-stanley/composeui-node-launcher@0.1.0-alpha.4 install { code: 1, signal: null }

5066 error command C:\Windows\system32\cmd.exe /d /s /c node ./src/cli/install.js
5067 error file:///C:/Users/XXX/source/repos/ComposeUI/src/shell/js/composeui-node-launcher/src/cli/install.js:15
5067 error import pkg from './../../package.json' assert { type: "json" };
5067 error                                        ^^^^^^
5067 error
5067 error SyntaxError: Unexpected identifier 'assert'
5067 error     at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
5067 error     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:103:185061 verbose stack Error: command failed
5061 verbose stack     at promiseSpawn (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
5061 verbose stack     at spawnWithShell (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
5061 verbose stack     at promiseSpawn (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
5061 verbose stack     at runScriptPkg (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
5061 verbose stack     at runScript (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
5061 verbose stack     at C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
5061 verbose stack     at run (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
5061 verbose stack     at C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
5061 verbose stack     at new Promise (<anonymous>)
5061 verbose stack     at callLimit (C:\Users\XXX\AppData\Roaming\nvm\v23.3.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
5062 verbose pkgid @morgan-stanley/composeui-node-launcher@0.1.0-alpha.4
5063 error code 1
5064 error path C:\Users\XXX\Source\Repos\ComposeUI\src\shell\js\composeui-node-launcher
5065 error command failed
5066 error command C:\Windows\system32\cmd.exe /d /s /c node ./src/cli/install.js
5067 error file:///C:/Users/XXX/source/repos/ComposeUI/src/shell/js/composeui-node-launcher/src/cli/install.js:15
5067 error import pkg from './../../package.json' assert { type: "json" };)
5067 error     at #translate (node:internal/modules/esm/loader:437:12)
5067 error     at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:484:27)
5067 error     at async ModuleJob._link (node:internal/modules/esm/module_job:115:19)
5067 error
5067 error Node.js v23.3.0
5068 silly unfinished npm timer reify 1733607435735
5069 silly unfinished npm timer reify:build 1733607564013
5070 silly unfinished npm timer build 1733607564013
5071 silly unfinished npm timer build:links 1733607571964
5072 silly unfinished npm timer build:run:install 1733607571966
5073 silly unfinished npm timer build:run:install:src/shell/js/composeui-node-launcher 1733607571966
5074 verbose cwd C:\Users\XXX\Source\Repos\ComposeUI
5075 verbose os Windows_NT 10.0.22621
5076 verbose node v23.3.0
5077 verbose npm  v10.9.0
5078 verbose exit 1
5079 verbose code 1
```

Thanks & Regards,
Rahul

**Comment by misrarah** [comment]
Projects build with node 20.18.1 and dotnet SDK 8.0
I'll send a PR with updated Readme and a global.json
